In [1]:
import numpy as np

#### In this lab, we will implement the multi-layer perceptron (MLP) algorithm for a single neuron. 

![The Multi-layer Perceptron Algorithm](mlp.png)

In [2]:
# let's implement the MLP algorithm on the XOR logic function
# In last week tutorial on single layer perceptron, we saw 
# it's implossible to get 100% accuracy on the XOR logic table (why?)
# now let's see if multi-layer perceptron, we will perform better
xordata = np.array([[0,0,0],[0,1,1],[1,0,1],[1,1,0]])
xordata

array([[0, 0, 0],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [3]:
# The inputs
inputs = xordata[:,:2]
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [4]:
# the targets 
targets = xordata[:,2:]
targets

array([[0],
       [1],
       [1],
       [0]])

In [5]:
# we will implement two layer perceptron: one hidden layer and one output layer 
# we will need to initialise two weights matrices, one for each layer. 
# the shape of hidden-layer weights matrix is deterimned by the samples features
# and by the number of hidden neurons. The shape of the output-layer weights matrix    
# is determined by the number of hidden neurons and the number of outputs
nin = np.shape(inputs)[1]
nout = np.shape(targets)[1]
nhidden = 2 # this is chosen to be small because our dataset is small but you could try different number 

weights1 = (np.random.rand(nin+1,nhidden)-0.5)*2/np.sqrt(nin) # hidden-layer weights
weights2 = (np.random.rand(nhidden+1,nout)-0.5)*2/np.sqrt(nhidden) # output-layer weights

In [6]:
# adding bias to the inputs 
ndata = np.shape(inputs)[0] # number of samples
inputs = np.concatenate((inputs,-np.ones((ndata,1))),axis=1)
inputs

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

In [7]:
# this is empty arrays to store the update weights 
updatew1 = np.zeros((np.shape(weights1)))
updatew2 = np.zeros((np.shape(weights2)))

In [10]:
niterations = 5000
eta = 0.25 # learning rate 
# training loop 
beta = 1 
for n in range(niterations):
    
    ## forward phase
    hidden = np.dot(inputs,weights1) 
    hidden = 1.0/(1.0+np.exp(-beta*hidden)) # activation fucntion: sigmoid function (4.5)
    hidden = np.concatenate((hidden,-np.ones((np.shape(inputs)[0],1))),axis=1) # adding bias
    
    # the output neuron is linear 
    outputs = np.dot( hidden, weights2)
    
    
    
    # compute the error using the sum-of-squares error function
    error = 0.5*np.sum((outputs-targets)**2)
    if (n % 100) == 0:
        print("Iteration: ",n, " Error: ",error) 
    
    ## backward phase 
    deltao = (outputs-targets)/ndata # because the output layer is linear     
    deltah = hidden*beta*(1.0-hidden)*(np.dot(deltao,np.transpose(weights2))) # (4.9)
    
    # updating the weights 
    updatew1 = eta*(np.dot(np.transpose(inputs),deltah[:,:-1])) 
    updatew2 = eta*(np.dot(np.transpose(hidden),deltao))
    
    
    weights1 -= updatew1
    weights2 -= updatew2

Iteration:  0  Error:  0.4363173903701296
Iteration:  100  Error:  0.41444605946821805
Iteration:  200  Error:  0.3908969326820973
Iteration:  300  Error:  0.3681361890329023
Iteration:  400  Error:  0.3480922692712466
Iteration:  500  Error:  0.33158911364398336
Iteration:  600  Error:  0.31851214740901307
Iteration:  700  Error:  0.3082980029714214
Iteration:  800  Error:  0.30030964507471963
Iteration:  900  Error:  0.2940008541740766
Iteration:  1000  Error:  0.2889510193964272
Iteration:  1100  Error:  0.28484990428985973
Iteration:  1200  Error:  0.2814716724227573
Iteration:  1300  Error:  0.27865168373707194
Iteration:  1400  Error:  0.2762688748246722
Iteration:  1500  Error:  0.27423316085677507
Iteration:  1600  Error:  0.27247662127427585
Iteration:  1700  Error:  0.27094735826634697
Iteration:  1800  Error:  0.2696051980796707
Iteration:  1900  Error:  0.2684186552355109
Iteration:  2000  Error:  0.26736276480766863
Iteration:  2100  Error:  0.2664175159475305
Iteration:  

In [9]:
outputs = np.where(outputs>0.5,1,0)
outputs

array([[0],
       [0],
       [1],
       [1]])