In [1]:
import numpy as np

#### In this lab, we will implement the perceptron algorithm for a single layer. 

![Perceptron Algorithm](pcn.png)

In [2]:
# Let's implement the algorithm on the AND logic function 
a = np.array([[0,0,0],[0,1,0],[1,0,0],[1,1,1]]) # AND logic table 
a

array([[0, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 1, 1]])

In [3]:
# This is the input
inputs = a[:,:2] 
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [4]:
# and this the target 
targets = a[:,2:]
targets

array([[0],
       [0],
       [0],
       [1]])

In [5]:
# set up the network size 
# We need to know the shape of the weights matrix 
# it is determined by the number of features in the input samples
# and the number of outputs in the samples 
nIn = np.shape(inputs)[1]
nOut = np.shape(targets)[1]
nIn, nOut

(2, 1)

In [8]:
# Initialise the weights to small (positive and negative) random numbers
# here we add one row to the weights matrix for the bias
weights = np.random.rand(nIn+1,nOut)*0.1-0.05
weights
# weights.shape

array([[-0.00687574],
       [ 0.01042767],
       [ 0.00881583]])

In [11]:
# Adding the bias to the inputs samples 
nData = np.shape(inputs)[0] # number of samples
inputs = np.concatenate((inputs,-np.ones((nData,1))),axis=1)
inputs

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

In [12]:
# training loop 
eta = 0.25 # the learning rate 
nIterations = 10
for n in range(nIterations):
    
    # Compute activations
    activations = np.dot(inputs, weights)
    
    # Threshold the activations
    activations = np.where(activations>0,1,0)
    
    # update the weights 
    weights -= eta*np.dot(np.transpose(inputs),activations-targets)

In [13]:
# now let's classify the inputs samples
outputs = np.dot(inputs,weights)
outputs = np.where(outputs>0,1,0)
outputs

array([[0],
       [0],
       [0],
       [1]])

In [15]:
# TODO: compute the accuracy 
num_correct = np.sum(outputs == targets)
accuracy  = float(num_correct / nData)
accuracy


1.0

In [16]:
# TODO: compute the Confusion matrix
nClasses = 2 # here we have two classes only 
cm = np.zeros((nClasses,nClasses))
for i in range(nClasses):
    for j in range(nClasses):
        cm[i,j] = np.sum(np.where(outputs==i,1,0)*np.where(targets==j,1,0))

cm      

array([[3., 0.],
       [0., 1.]])

In [17]:
# TDOD: can you test the implementation on the XOR logic function? 
b = np.array([[0,0,0],[0,1,1],[1,0,1],[1,1,0]]) # XOR logic table 
b
# Will we get 100% accuracies? if no, why? 

array([[0, 0, 0],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [19]:
inputs  = b[:,:2]
targets = b[:,2:]
nIn = np.shape(inputs)[1]
nOut = np.shape(targets)[1]
weights = np.random.rand(nIn+1,nOut)*0.1-0.05
nData = np.shape(inputs)[0] # number of samples
inputs = np.concatenate((inputs,-np.ones((nData,1))),axis=1)


eta = 0.25 # the learning rate 
nIterations = 10
for n in range(nIterations):
    
    # Compute activations
    activations = np.dot(inputs, weights)
    
    # Threshold the activations
    activations = np.where(activations>0,1,0)
    
    # update the weights 
    weights -= eta*np.dot(np.transpose(inputs),activations-targets)
    

outputs = np.dot(inputs,weights)
outputs = np.where(outputs>0,1,0)
num_correct = np.sum(outputs == targets) # number of correct classifications
accuracy = float(num_correct) / nData # accuracy 
accuracy

0.5

In [20]:
nClasses = 2 # here we have two classes only 
cm = np.zeros((nClasses,nClasses))
for i in range(nClasses):
    for j in range(nClasses):
        cm[i,j] = np.sum(np.where(outputs==i,1,0)*np.where(targets==j,1,0))

cm 

array([[2., 2.],
       [0., 0.]])