## Quickstart Tutorial on NumPy

### Here, we will learn how to use NumPy library. This tutoral is based on the [original NumPy tutorial](https://numpy.org/devdocs/user/quickstart.html). 

In [1]:
# importing numpy array
import numpy as np #To install: pip install numpy

### Array Creation

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [2]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [3]:
a.dtype

dtype('int64')

In [4]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [5]:
c = np.array([[1, 2, 3],[6, 5, 4]])

In [6]:
print(c)

[[1 2 3]
 [6 5 4]]


In [7]:
c.shape

(2, 3)

In [8]:
# creating an array full of zeros
z = np.zeros((2, 4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# To create sequences of numbers, NumPy provides the 'arange' function which is 
# analogous to the Python built-in range, but returns an array.
np.arange( 10, 40, 5)

array([10, 15, 20, 25, 30, 35])

### Basic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [10]:
a = np.array( [20,30,40,50] )

In [11]:
b = np.arange(4)

In [12]:
b

array([0, 1, 2, 3])

In [13]:
c = a-b
c

array([20, 29, 38, 47])

In [14]:
b**2

array([0, 1, 4, 9])

In [15]:
a<30

array([ True, False, False, False])

Unlike in many matrix languages, the product operator `*` operates elementwise in NumPy arrays. The matrix product can be performed using the `@` operator or the dot function method:

In [16]:
A = np.array( [[1,1],
               [0,1]] )

In [17]:
B = np.array( [[2,0],
               [3,4]] )

In [18]:
# elementwise product
A * B 

array([[2, 0],
       [0, 4]])

In [19]:
# matrix product
A @ B

array([[5, 4],
       [3, 4]])

In [20]:
# another matrix product
A.dot(B)

array([[5, 4],
       [3, 4]])

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [21]:
a = np.ones(3, dtype=np.int32)
a.dtype.name

'int32'

In [22]:
b = np.linspace(0,np.pi,3)
b.dtype.name

'float64'

In [23]:
c = a+b
c.dtype.name

'float64'

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the `ndarray` class.

In [24]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [29]:
a.sum()

6

In [31]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
# sum of each column
b.sum(axis=0) 

array([12, 15, 18, 21])

### Indexing, Slicing and Iterating

In [45]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [46]:
a[2:6]

array([  8,  27,  64, 125])

In [47]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [48]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [49]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
b[1,:] # second row

array([3, 4, 5])

In [52]:
b[:,-1] # last column

array([ 2,  5,  8, 11])

In [61]:
# iterating over rows
for row in b:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


### Shape Manipulation

In [67]:
rg = np.random.default_rng(1) # create instance of default random number generator
a = np.floor(10*rg.random((6,4)))
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.],
       [3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [68]:
a.shape

(6, 4)

In [69]:
a.T

array([[5., 3., 5., 3., 1., 7.],
       [9., 4., 0., 7., 4., 2.],
       [1., 8., 7., 3., 2., 4.],
       [9., 4., 5., 4., 2., 9.]])

In [70]:
a.T.shape

(4, 6)

The **reshape** function returns its argument with a modified shape, whereas the **ndarray.resize** method modifies the array itself:

In [72]:
a.resize((3,8))

In [73]:
a.shape

(3, 8)

In [76]:
a.reshape((12,-1))


array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.],
       [5., 0.],
       [7., 5.],
       [3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [77]:
a.shape

(3, 8)

### Linear Algebra

In [85]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [86]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [87]:
# the inverse 
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [89]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [90]:
np.trace(I)

4.0

In [91]:
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [94]:
np.linalg.eig(I)

(array([1., 1., 1., 1.]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

## Lab Exercises

#### 

In [5]:
m = np.arange(16).reshape(4,4)
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [7]:
# TODO: Compute the sum of the diagonal element of the m matrix.
# hint: np.trace() 
result = None

In [8]:
print(result)

None


In [2]:
x = np.arange(6)
# TODO: Get the powers of an array values element-wise and store it in y
y = None

In [ ]:
# TODO: compute the average, variance, standard deviation of the below array elements
z = np.arange(16).reshape(3,4)
average = None
var = None
std = None

####  solve a system of three linear equations, shown below 
4x + 3y + 2z = 25 
<br>
-2x + 2y + 3z = -10
<br>
3x -5y + 2z = -4

In [ ]:
# TDOD: Method 1: Solve the linear system using only the inverse and the dot product 
# hint: np.linalg.inv()
A = None # array of the coefficients
b = None # array as the right-hand side of the equations
X = None # array for the variable values of x,y and z

In [ ]:
# TDOD: Method 1: Solve the linear system using np.linalg.solve()
A = None # array of the coefficients
b = None # array as the right-hand side of the equations
X = None # array for the variable values of x,y and z